name: Deploy over SSH

on:
  workflow_call:
    inputs:
      REMOTE_FOLDER:
        required: true
        type: string
      APP_NAME:
        required: true
        type: string
      PRE_RUN_SCRIPT:
        required: false
        type: string
    secrets:
      SERVER_IP:
        required: true
      SERVER_SSH_KEY:
        required: true
      NOTIFICATION_URL:
        required: true
      NOTIFICATION_SECRET:
        required: true

jobs:
  
  deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Notify Start
        uses: fjogeleit/http-request-action@master
        continue-on-error: true
        with:
          url: ${{ secrets.NOTIFICATION_URL }}
          method: 'POST'
          data: '{ "message": "${{ inputs.APP_NAME }} build triggered", "app": "octo", "auth": "${{ secrets.NOTIFICATION_SECRET }}" }'

      - name: Run pre-run script if provided
        if: "${{ inputs.PRE_RUN_SCRIPT != '' }}"
        run: | 
          chmod +x ${{ inputs.PRE_RUN_SCRIPT }}
          ${{ inputs.PRE_RUN_SCRIPT }}

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script_stop: true
          script: |
            cd ${{ inputs.REMOTE_FOLDER }}
            docker-compose down || true
            git pull
            docker-compose up -d --build

      - name: Notify Finish
        if: success()
        uses: fjogeleit/http-request-action@master
        with:
          url: ${{ secrets.NOTIFICATION_URL }}
          method: 'POST'
          data: '{ "message": "Deployed ${{ inputs.APP_NAME }}!", "app": "octo", "auth": "${{ secrets.NOTIFICATION_SECRET }}" }'

      - name: Notify Failure
        if: failure()
        uses: fjogeleit/http-request-action@master
        with:
          url: ${{ secrets.NOTIFICATION_URL }}
          method: 'POST'
          data: '{ "message": "${{ inputs.APP_NAME }} failed to deploy!", "emergency": true, "app": "octo", "auth": "${{ secrets.NOTIFICATION_SECRET }}" }'

